// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace eShop.DataBaseRepository.Db.Models
{
    public partial class Users
    {
        public Users()
        {
            Orders = new HashSet<Orders>();
            UsersInRoles = new HashSet<UsersInRoles>();
        }

        public Guid Id { get; set; }
        public bool IsActive { get; set; }
        public string ActivationCode { get; set; }
        public string FirtsName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PasswordHash { get; set; }
        public Guid? SessionId { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime? DateChanged { get; set; }
        public DateTime? DateDeleted { get; set; }

        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<UsersInRoles> UsersInRoles { get; set; }
    }
}